name: DevSecOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "Tests failed but continuing..."

      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run OWASP Dependency-Check scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            owasp/dependency-check \
            --project "MyApp" \
            --scan /src \
            --format HTML \
            --out /src/reports

      - name: List reports directory
        run: ls -la reports/

      - name: Upload OWASP Dependency-Check report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
